apiVersion: v1
data:
  checksum-nodes: "5"
  data-nodes: "2"
kind: ConfigMap
metadata:
  name: data-service-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: data-service
        imagePullPolicy: Never
        env:
        - name: DATA_NODES
          valueFrom:
            configMapKeyRef:
              name: data-service-config
              key: data-nodes
        - name: CHECKSUM_NODES
          valueFrom:
            configMapKeyRef:
              name: data-service-config
              key: checksum-nodes
        readinessProbe:
          httpGet:
            port: 80
            path: /data-service/health
          initialDelaySeconds: 15
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.1
            memory: 128Mi
          limits:
            cpu: 0.1
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: data-service
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nansi
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: data-service
spec:
  rules:
  - host: nansi8.net
    http:
      paths:
      - backend:
          serviceName: data-service
          servicePort: 80
        path: /data-service

